config/routes.rb
Rails.application.routes.draw do
  resources :capstones
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/capstone.rb
class Capstone < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/capstones_controller.rb
class CapstonesController < ApplicationController
  before_action :set_capstone, only: [:show, :edit, :update, :destroy]

  # GET /capstones
  # GET /capstones.json
  def index
    @capstones = Capstone.all
  end

  # GET /capstones/1
  # GET /capstones/1.json
  def show
  end

  # GET /capstones/new
  def new
    @capstone = Capstone.new
  end

  # GET /capstones/1/edit
  def edit
  end

  # POST /capstones
  # POST /capstones.json
  def create
    @capstone = Capstone.new(capstone_params)

    respond_to do |format|
      if @capstone.save
        format.html { redirect_to @capstone, notice: 'Capstone was successfully created.' }
        format.json { render :show, status: :created, location: @capstone }
      else
        format.html { render :new }
        format.json { render json: @capstone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /capstones/1
  # PATCH/PUT /capstones/1.json
  def update
    respond_to do |format|
      if @capstone.update(capstone_params)
        format.html { redirect_to @capstone, notice: 'Capstone was successfully updated.' }
        format.json { render :show, status: :ok, location: @capstone }
      else
        format.html { render :edit }
        format.json { render json: @capstone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /capstones/1
  # DELETE /capstones/1.json
  def destroy
    @capstone.destroy
    respond_to do |format|
      format.html { redirect_to capstones_url, notice: 'Capstone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_capstone
      @capstone = Capstone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def capstone_params
      params.require(:capstone).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    "Hello"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/capstones_helper.rb
module CapstonesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/capstones/_form.html.erb
<%= form_for(capstone) do |f| %>
  <% if capstone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(capstone.errors.count, "error") %> prohibited this capstone from being saved:</h2>

      <ul>
      <% capstone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/capstones/edit.html.erb
<h1>Editing Capstone</h1>

<%= render 'form', capstone: @capstone %>

<%= link_to 'Show', @capstone %> |
<%= link_to 'Back', capstones_path %>

app/views/capstones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Capstones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @capstones.each do |capstone| %>
      <tr>
        <td><%= capstone.name %></td>
        <td><%= link_to 'Show', capstone %></td>
        <td><%= link_to 'Edit', edit_capstone_path(capstone) %></td>
        <td><%= link_to 'Destroy', capstone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Capstone', new_capstone_path %>

app/views/capstones/new.html.erb
<h1>New Capstone</h1>

<%= render 'form', capstone: @capstone %>

<%= link_to 'Back', capstones_path %>

app/views/capstones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @capstone.name %>
</p>

<%= link_to 'Edit', edit_capstone_path(@capstone) %> |
<%= link_to 'Back', capstones_path %>

app/views/home/index.html.erb
<h2> Hello. </h2>
<h3><%= link_to "See Capstones", capstones_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CapstoneNinja</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1> CAPSTONE NINJA </h1>
    <%= yield %>
  </body>
</html>